//COURSE LIST
export const FETCH_COURSES_PENDING = 'FETCH_COURSES_PENDING'
export const FETCH_COURSES_SUCCESS = 'FETCH_COURSES_SUCCESS'
export const FETCH_COURSES_FAIL = 'FETCH_COURSES_FAIL'
export const DELETE_COURSE = 'DELETE_COURSE'

////COURSE DETAIL FIRST FETCH
export const FETCH_COURSE_PENDING = 'FETCH_COURSE_PENDING'
export const FETCH_COURSE_FAIL = 'FETCH_COURSE_FAIL'
export const FETCH_COURSE_SUCCESS = 'FETCH_COURSE_INFO_SUCCESS'
//GOAL
export const FETCH_COURSE_GOAL_PENDING = 'FETCH_COURSE_GOAL_PENDING'
export const FETCH_COURSE_GOAL_FAIL = 'FETCH_COURSE_GOAL_FAIL'
export const FETCH_COURSE_GOAL_SUCCESS = 'FETCH_COURSE_GOAL_SUCCESS'
export const DELETE_COURSE_GOAL_SUCCESS = 'DELETE_COURSE_GOAL_SUCCESS'
export const UPDATE_COURSE_GOAL_SUCCESS = 'UPDATE_COURSE_GOAL_SUCCESS'
//OUTCOME
export const FETCH_COURSE_OUTCOME_PENDING = 'FETCH_COURSE_OUTCOME_PENDING'
export const FETCH_COURSE_OUTCOME_FAIL = 'FETCH_COURSE_OUTCOME_FAIL'
export const FETCH_COURSE_OUTCOME_SUCCESS = 'FETCH_COURSE_OUTCOME_SUCCESS'
export const DELETE_COURSE_OUTCOME_SUCCESS = 'DELETE_COURSE_OUTCOME_SUCCESS'
export const UPDATE_COURSE_OUTCOME_SUCCESS = 'UPDATE_COURSE_OUTCOME_SUCCESS'
//EVUALATE
export const FETCH_COURSE_EVUALATE_FAIL ='FETCH_COURSE_EVUALATE_FAIL'
export const FETCH_COURSE_EVUALATE_PENDING ='FETCH_COURSE_EVUALATE_PENDING'
export const FETCH_COURSE_EVUALATE_SUCCESS ='FETCH_COURSE_EVUALATE_SUCCESS'
export const UPDATE_COURSE_EVUALATE_SUCCESS = 'UPDATE_COURSE_EVUALATE_SUCCESS'
export const DELETE_COURSE_EVUALATE_SUCCESS = 'DELETE_COURSE_EVUALATE_SUCCESS'
//CONTENT
export const FETCH_COURSE_CONTENT_SUCCESS = 'FETCH_COURSE_CONTENT_SUCCESS'
export const FETCH_COURSE_CONTENT_PENDING = 'FETCH_COURSE_CONTENT_PENDING'
export const FETCH_COURSE_CONTENT_FAIL = 'FETCH_COURSE_CONTENT_FAIL'
export const DELETE_COURSE_CONTENT_SUCCESS = 'DELETE_COURSE_CONTENT_SUCCESS'
export const UPDATE_COURSE_CONTENT_SUCCESS = 'UPDATE_COURSE_CONTENT_SUCCESS'